export {default as About } from './About'
export { default as Project} from './Project'
export { default as Footer} from './Footer'
export {default as ContactForm} from './ContactForm'
export { default as EducationComponent} from './EducationComponent'
export { default as TechSkills} from './TechSkills'